### ISSUE TITLE
Start the faucet in command line:

### ISSUE THREAD

**Issue by hbadih** [input-output-hk/etc-client#1126]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 4.15.0-20-generic]

**Additional context**

I am trying to start the faucet in step 5 when I run this command sbt -Dconfig.file=src/universal/conf/faucet.conf "run faucet"
I get this error

[0mcom.typesafe.config.ConfigException$Missing: src\universal\conf\faucet.conf: 86: No configuration setting found for key 'health'←[0m←[0J
this is running in Windows 10
any help?????????????????

**Comment by hbadih** [comment]
Error

C:\mantis>sbt -Dconfig.file=src/universal/conf/faucet.conf "run faucet"
[info] welcome to sbt 1.5.4 (Oracle Corporation Java 16.0.2)
[info] loading settings for project mantis-build from plugins.sbt,scalapb.sbt ...
[info] loading project definition from C:\mantis\project
[info] loading settings for project node from build.sbt,version.sbt ...
[info] set current project to mantis (in build file:/C:/mantis/)
[warn] there are 2 keys that are not used by any other settings/tasks:
[warn]
[warn] * ThisBuild / jdkPackagerType
[warn]   +- C:\mantis\build.sbt:268
[warn] * ThisBuild / organization
[warn]   +- C:\mantis\build.sbt:22
[warn]
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
[info] running io.iohk.ethereum.App faucet
16:12:51,248 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:12:51,249 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:12:51,249 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/mantis/target/bg-jobs/sbt_a02e15a/job-1/target/94d912b7/711dede4/mantis_2.13-3.4.0-SNAPSHOT.jar!/logback.xml]
16:12:51,250 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:12:51,250 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/mantis/target/bg-jobs/sbt_a02e15a/job-1/target/94d912b7/711dede4/mantis_2.13-3.4.0-SNAPSHOT.jar!/logback.xml]
16:12:51,250 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/mantis/target/bg-jobs/sbt_a02e15a/target/ea595944/6c4cc090/org.jupnp.tool-2.5.2.jar!/logback.xml]
16:12:51,262 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@f11380e - URL [jar:file:/C:/mantis/target/bg-jobs/sbt_a02e15a/job-1/target/94d912b7/711dede4/mantis_2.13-3.4.0-SNAPSHOT.jar!/logback.xml] is not of type file
16:12:51,280 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:12:51,284 |-INFO in ch.qos.logback.core.joran.action.NewRuleAction - About to add new Joran parsing rule [*/load,io.iohk.ethereum.utils.LoadFromApplicationConfiguration].
16:12:51,398 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:12:51,401 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:12:51,404 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:12:51,425 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:12:51,425 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STASH]
16:12:51,453 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.fieldnames.LogstashFieldNames] for [fieldNames] property
16:12:51,593 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:12:51,596 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
16:12:51,600 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@49ee8e34 - Will use zip compression
16:12:51,600 |-WARN in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@49ee8e34 - Large window sizes are not allowed.
16:12:51,600 |-WARN in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@49ee8e34 - MaxIndex reduced to 21
16:12:51,602 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:12:51,602 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: C:\Users\badihh/.mantis-faucet/logs/faucet.log
16:12:51,602 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [C:\Users\badihh/.mantis-faucet/logs/faucet.log]
16:12:51,603 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [io.prometheus.client.logback.InstrumentedAppender]
16:12:51,609 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [METRICS]
16:12:51,609 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:12:51,741 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:12:51,741 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
16:12:51,741 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [METRICS] to Logger[ROOT]
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.netty] to WARN
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.iohk.scalanet] to INFO
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.iohk.scalanet.discovery.ethereum.v4.DiscoveryService] to WARN
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.iohk.ethereum.blockchain.sync.SyncController] to INFO
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.iohk.ethereum.network.PeerActor] to INFO
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.iohk.ethereum.network.rlpx.RLPxConnectionHandler] to INFO
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.iohk.ethereum.vm.VM] to OFF
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.jupnp.QueueingThreadPoolExecutor] to WARN
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.jupnp.util.SpecificationViolationReporter] to ERROR
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.jupnp.protocol.RetrieveRemoteDescriptors] to ERROR
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:12:51,742 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4bf033b - Registering current configuration as safe fallback point
2021-10-07 16:12:52,207 INFO  [akka.event.slf4j.Slf4jLogger] - Slf4jLogger started
2021-10-07 16:12:52,672 INFO  [i.iohk.ethereum.faucet.FaucetHandler] - Initialization called (faucet unavailable)
[error] (run-main-0) com.typesafe.config.ConfigException$Missing: src\universal\conf\faucet.conf: 86: No configuration setting found for key 'health'
[error] com.typesafe.config.ConfigException$Missing: src\universal\conf\faucet.conf: 86: No configuration setting found for key 'health'
[error]         at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
[error]         at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
[error]         at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
[error]         at com.typesafe.config.impl.SimpleConfig.getDuration(SimpleConfig.java:324)
[error]         at io.iohk.ethereum.jsonrpc.NodeJsonRpcHealthChecker$JsonRpcHealthConfig$.apply(NodeJsonRpcHealthChecker.scala:144)
[error]         at io.iohk.ethereum.jsonrpc.server.controllers.JsonRpcBaseController$JsonRpcConfig$$anon$1.<init>(JsonRpcBaseController.scala:154)
[error]         at io.iohk.ethereum.jsonrpc.server.controllers.JsonRpcBaseController$JsonRpcConfig$.apply(JsonRpcBaseController.scala:138)
[error]         at io.iohk.ethereum.faucet.jsonrpc.JsonRpcConfigBuilder.jsonRpcConfig(FaucetBuilder.scala:73)
[error]         at io.iohk.ethereum.faucet.jsonrpc.JsonRpcConfigBuilder.jsonRpcConfig$(FaucetBuilder.scala:73)
[error]         at io.iohk.ethereum.faucet.jsonrpc.FaucetServer.jsonRpcConfig$lzycompute(FaucetBuilder.scala:115)
[error]         at io.iohk.ethereum.faucet.jsonrpc.FaucetServer.jsonRpcConfig(FaucetBuilder.scala:115)
[error]         at io.iohk.ethereum.faucet.jsonrpc.FaucetJsonRpcControllerBuilder.$init$(FaucetBuilder.scala:80)
[error]         at io.iohk.ethereum.faucet.jsonrpc.FaucetServer.<init>(FaucetBuilder.scala:116)
[error]         at io.iohk.ethereum.faucet.Faucet$.main(Faucet.scala:9)
[error]         at io.iohk.ethereum.App$.main(App.scala:33)
[error]         at io.iohk.ethereum.App.main(App.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
2021-10-07 16:12:53,974 INFO  [i.i.e.faucet.jsonrpc.WalletService] - unlock wallet for use in faucet (0x7988edc737f88b92ce1fd1aa9509674808ac912d)
2021-10-07 16:12:53,983 INFO  [i.iohk.ethereum.faucet.FaucetHandler] - Faucet initialization succeeded

[warn] Canceling execution...
Cancelled: run faucet
